id: ID3D0BED6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:03:47+00:00'
last_modified: '2022-06-09T04:57:12.535024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29898
  title: ཟློས་གར་དང་མཁས་འཇུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FE9E:
      image_group_id: I5720
      title: ''
      total_pages: 637
      order: 1
      base_file: FE9E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
