id: P007106
initial_creation_type: ocr
source_metadata:
  id: bdr:W29898
  title: ཟློས་གར་དང་མཁས་འཇུག
  author: ''
  volumes:
    1a9df139a8f549168b1f7cdba7e45039:
      image_group_id: I5720
      title: ''
      volume_number: 1
      total_pages: 637
      base_file: v001.txt
ebook_metadata:
  title: ཟློས་གར་དང་མཁས་འཇུག
  author: ''
  sku: P007106
  cover: cover.jpg
  layers:
  - pagination
