id: P007106
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:42:01.031577
source_metadata:
  id: bdr:W29898
  title: ཟློས་གར་དང་མཁས་འཇུག
  author: ''
  volumes:
    1a9df139a8f549168b1f7cdba7e45039:
      image_group_id: I5720
      title: ''
      volume_number: 1
      total_pages: 637
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
